- hosts: kubernetes_master
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw
 
  - name: set join command
    set_fact:
     join_command: "{{ join_command_raw.stdout_lines[0] }}"
 
- hosts: kubernetes_slave
  become: yes
  tasks:
  - name: remove swap
    shell: "swapoff -a"
 
  - name: join cluster	
    shell: "{{ hostvars['kubernetes_master'].join_command }}"
